import enLocale from 'element-ui/lib/locale/lang/en';
import zhLocale from 'element-ui/lib/locale/lang/zh-CN';

export default {
  cn: {
    myWms: '我的WMS',
    newStore: '新建仓库',
    StoreLease: '仓库租赁',
    authManage: '认证管理',
    authList: '创建仓库权限认证',
    renterList: '租赁仓库权限认证',
    userManage: '用户管理',
    storeManage: '仓库设置',
    storeInfo: '创建仓库详情',
    home: '首页',
    myAuthentication: '我的认证',
    homeSetup: '首页设置',
    editPassword: '修改密码',
    PleaseEnterTheMailbox: '请输入邮箱',
    PleaseInputApassword: '请输入密码',
    authenticationForm: '创建认证',
    addStoreManage: '创建仓库',
    storeName: '仓库名称',
    addCargoShelf: '添加货架',
    BasicsConfig: '基础配置',
    addCargoArea: '添加货区',
    seeApplication: '查看申请',
    StoreLeases: '仓库设置',
    addBatchType: '添加入库单分类',
    MayApplyStore: '查看已申请仓库',
    addOrderType: '添加出库单分类',
    addCargoTray: '添加托盘',
    addCargoKep: '添加篮筐',
    MayApplyStoreInfo: ' 租赁',
    LeaseAudit: '租赁审核',
    ...zhLocale,
  },
  en: {
    myWms: '我的WMS',
    newStore: '新建仓库',
    StoreLease: '仓库租赁',
    authManage: '认证管理',
    authList: '创建仓库权限认证',
    renterList: '租赁仓库权限认证',
    userManage: '用户管理',
    storeManage: '仓库设置',
    storeInfo: '创建仓库详情',

    home: '首页',
    myAuthentication: '我的认证',
    homeSetup: '首页设置',
    editPassword: '修改密码',
    PleaseEnterTheMailbox: '请输入邮箱',
    PleaseInputApassword: '请输入密码',
    authenticationForm: '创建认证',
    addStoreManage: '创建仓库',
    storeName: '仓库名称',
    addCargoShelf: '添加货架',
    BasicsConfig: '基础配置',
    addCargoArea: '添加货区',
    seeApplication: '查看申请',
    MayApplyStore: '查看已申请仓库',
    addOrderType: '添加出库单分类',
    addCargoTray: '添加托盘',
    addCargoKep: '添加篮筐',
    StoreLeases: '租赁仓库',
    addBatchType: '添加入库单分类',
    MyGoodsList: '我的商品库',
    goodsAddEdit: '新增商品',
    inventoryManage: '库存管理',
    goodsAlarm: '商品报警',
    inboundList: '入库单列表',
    addInbound: '添加入库单',
    outboundList: '出库单列表',
    logisticsQuery: '物流查询',
    userList: '用户列表',
    userGroupList: '用户组列表',
    userGroupAdd: '添加员工组',
    userAdd: '添加员工',
    MayApplyStoreInfo: ' 租赁',
    LeaseAudit: '租赁审核',
    ...enLocale,
  },
};
